server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.92.227.250:3306/recommend?serverTimezone=UTC
    username: username
    password: password
mybatis:
  configuration:
    map-underscore-to-camel-case: true
